# Generated by Django 2.2 on 2020-09-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=100)),
                ('nama_dosen', models.CharField(max_length=100)),
                ('kelompok', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Staf',
        ),
    ]
