# Generated by Django 2.2 on 2020-10-08 02:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mitra', '0002_auto_20200924_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateTimeField(default=datetime.datetime.now)),
                ('desc', models.TextField()),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mahasiswas', to=settings.AUTH_USER_MODEL)),
                ('nama_mitra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mitra.Mitra')),
            ],
        ),
    ]
