# Generated by Django 2.2 on 2020-09-24 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pkl',
            old_name='nama',
            new_name='nama_mitra',
        ),
    ]
