# Generated by Django 2.2 on 2020-09-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0002_auto_20200924_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='pkl',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
    ]
