# Generated by Django 2.2 on 2020-09-24 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0003_pkl_is_approve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pkl',
            old_name='is_approve',
            new_name='approve',
        ),
    ]
